/*
 * rtu_return_values.h
 *
 *  Created on: 18.09.2020
 *      Author: mateusz
 */

#ifndef INCLUDE_MODBUS_RTU_RTU_RETURN_VALUES_H_
#define INCLUDE_MODBUS_RTU_RTU_RETURN_VALUES_H_

#define MODBUS_RET_UNINITIALIZED 	-1
#define MODBUS_RET_OK				0
#define MODBUS_RET_TOO_SHORT		1
#define MODBUS_RET_WRONG_FUNCTION	2
#define MODBUS_RET_REQUEST_GEN_ERR	3
#define MODBUS_RET_GOT_EXCEPTION	4
#define MODBUS_RET_NOT_AVALIABLE	5
#define MODBUS_RET_DEGRADED			6
#define MODBUS_RET_UNEXP_SLAVE_ADR	7

#endif /* INCLUDE_MODBUS_RTU_RTU_RETURN_VALUES_H_ */
