/*
 * events_gsm_gprs.h
 *
 *  Created on: Jul 28, 2024
 *      Author: mateusz
 */

#ifndef EVENTS_DEFINITIONS_EVENTS_GSM_GPRS_H_
#define EVENTS_DEFINITIONS_EVENTS_GSM_GPRS_H_


#define EVENTS_GSM_GPRS_ERR_APN_CONFIGURATION_MISSING		(0x01U)
#define EVENTS_GSM_GPRS_WARN_ASYNC_MSG_DETECTED				(0x02U)
#define EVENTS_GSM_GPRS_ERR_SIM_CARD_STATUS					(0x03U)
#define EVENTS_GSM_GPRS_WARN_NOT_REGISTERED_TO_NETWORK		(0x04U)

#define EVENTS_GSM_GPRS_REGISTERED_NETWORK					(0xE0U)
#define EVENTS_GSM_GPRS_SIGNAL_LEVEL						(0xE1U)
#define EVENTS_GSM_GPRS_IMSI								(0xE2U)
#define EVENTS_GSM_GPRS_IP_ADDRESS							(0xE3U)

//EVENTS_GSM_GPRS_IP_ADDRESS

#endif /* EVENTS_DEFINITIONS_EVENTS_GSM_GPRS_H_ */
