/*
 * events_drv_spi.h
 *
 *  Created on: Jul 28, 2024
 *      Author: mateusz
 */

#ifndef EVENTS_DEFINITIONS_EVENTS_DRV_SPI_H_
#define EVENTS_DEFINITIONS_EVENTS_DRV_SPI_H_


#define EVENTS_DRV_SPI_MAX31865_ERROR_INCONSIST_RESULTS				(0x70U)
#define EVENTS_DRV_SPI_MAX31865_ERROR_SPI_WHILE_REG_REQUEST			(0x71U)


#endif /* EVENTS_DEFINITIONS_EVENTS_DRV_SPI_H_ */
