/*
 * events_pwr_save.h
 *
 *  Created on: Jul 28, 2024
 *      Author: mateusz
 */

#ifndef EVENTS_DEFINITIONS_EVENTS_PWR_SAVE_H_
#define EVENTS_DEFINITIONS_EVENTS_PWR_SAVE_H_

#define EVENTS_PWR_SAVE_BATT_LOW_GOING_SLEEP			0x00u

#define EVENTS_PWR_SAVE_GO_TO_INTERMEDIATE_SLEEP		0x10u
#define EVENTS_PWR_SAVE_WOKEN_UP_RTC_INTERRUPT			0x11u
#define EVENTS_PWR_SAVE_WOKEN_UP_AFTER_LAST_SLEEP		0x12u
#define EVENTS_PWR_SAVE_WOKEN_UP_EXITED					0x13u


#endif /* EVENTS_DEFINITIONS_EVENTS_PWR_SAVE_H_ */
