/*
 * evnets_drv_anemometer.h
 *
 *  Created on: Jul 28, 2024
 *      Author: mateusz
 */

#ifndef EVENTS_DEFINITIONS_EVENTS_DRV_ANEMOMETER_H_
#define EVENTS_DEFINITIONS_EVENTS_DRV_ANEMOMETER_H_


#define EVENTS_DRV_ANEMOMETER_WARN_NO_PULSES_INT_FIRED		(0x01U)
#define EVENTS_DRV_ANEMOMETER_WARN_EXCESIVE_SLEW			(0x02U)

#define EVENTS_DRV_ANEMOMETER_ERROR_UF_CONV_NOT_WORKING		(0x03U)
#define EVENTS_DRV_ANEMOMETER_ERROR_UF_FREQ_TOO_HI			(0x04U)

#define EVENTS_DRV_ANEMOMETER_WARN_QF_NOT_FULL				(0x05U)

#endif /* EVENTS_DEFINITIONS_EVENTS_DRV_ANEMOMETER_H_ */
