/*
 * events_aprsis.h
 *
 *  Created on: Jul 28, 2024
 *      Author: mateusz
 */

#ifndef EVENTS_DEFINITIONS_EVENTS_APRSIS_H_
#define EVENTS_DEFINITIONS_EVENTS_APRSIS_H_


#define EVENTS_APRSIS_ERROR_IM_NOT_OK_LAST_KEEPALIVE				(0x01U)
#define EVENTS_APRSIS_ERROR_IM_NOT_OK_LAST_TRANSMIT_LONG			(0x02U)

#define EVENTS_APRSIS_WARN_AUTH_FAILED					(0x03U)
#define EVENTS_APRSIS_WARN_TIMEOUT_WAITING_AUTH			(0x04U)
#define EVENTS_APRSIS_WARN_NO_HELLO_MESSAGE				(0x05U)
#define EVENTS_APRSIS_WARN_TIMEOUT_WAITING_HELLO_MSG	(0x06U)
#define EVENTS_APRSIS_WARN_CONNECT_FAILED				(0x07U)

#define EVENTS_APRSIS_WARN_WRONG_STATE					(0x08U)

#define EVENTS_APRSIS_WARN_DEAD_KEEPALIVE				(0x09U)
#define EVENTS_APRSIS_WARN_DEAD_TRANSMIT				(0x09U)

#endif /* EVENTS_DEFINITIONS_EVENTS_APRSIS_H_ */
