/*
 * events_pwr_save.h
 *
 *  Created on: Jul 28, 2024
 *      Author: mateusz
 */

#ifndef EVENTS_DEFINITIONS_EVENTS_PWR_SAVE_H_
#define EVENTS_DEFINITIONS_EVENTS_PWR_SAVE_H_

#define EVENTS_PWR_SAVE_BATT_LOW_GOING_SLEEP			0x00u

#define EVENTS_PWR_SAVE_GO_TO_INTERMEDIATE_SLEEP		0x10u
#define EVENTS_PWR_SAVE_WOKEN_UP_RTC_INTERRUPT			0x11u
#define EVENTS_PWR_SAVE_WOKEN_UP_AFTER_LAST_SLEEP		0x12u
#define EVENTS_PWR_SAVE_WOKEN_UP_EXITED					0x13u
#define EVENTS_PWR_SAVE_SWITCHING_MODE					0x14u
#define EVENTS_PWR_SAVE_GO_TO_SLEEP						0x15u

#define EVENTS_PWR_SAVE_STATE_C0						0xC0u
#define EVENTS_PWR_SAVE_STATE_C1						0xC1u
#define EVENTS_PWR_SAVE_STATE_C2						0xC2u
#define EVENTS_PWR_SAVE_STATE_C3						0xC3u
#define EVENTS_PWR_SAVE_STATE_M4						0xC4u
#define EVENTS_PWR_SAVE_STATE_M4A						0xC5u
#define EVENTS_PWR_SAVE_STATE_I5						0xC6u
#define EVENTS_PWR_SAVE_STATE_L6						0xC7u
#define EVENTS_PWR_SAVE_STATE_L7						0xC8u

#endif /* EVENTS_DEFINITIONS_EVENTS_PWR_SAVE_H_ */
