/*
 * events_pwr_save.h
 *
 *  Created on: Jul 28, 2024
 *      Author: mateusz
 */

#ifndef EVENTS_DEFINITIONS_EVENTS_PWR_SAVE_H_
#define EVENTS_DEFINITIONS_EVENTS_PWR_SAVE_H_

#define EVENTS_PWR_SAVE_BATT_LOW_GOING_SLEEP				0x00u
#define EVENTS_PWR_SAVE_ERROR_RTC_WHILE_GOING_L7_SLEEP		0xA0u
#define EVENTS_PWR_SAVE_CYCLIC_GOING_L7_SLEEP				0x70u


#endif /* EVENTS_DEFINITIONS_EVENTS_PWR_SAVE_H_ */
