/*
 * events_wx_handler.h
 *
 *  Created on: Jul 28, 2024
 *      Author: mateusz
 */

#ifndef EVENTS_DEFINITIONS_EVENTS_WX_HANDLER_H_
#define EVENTS_DEFINITIONS_EVENTS_WX_HANDLER_H_


#define EVENTS_WX_HANDLER_WARN_TEMPERATURE_INT_FAILED		(0x01U)
#define EVENTS_WX_HANDLER_WARN_TEMPERATURE_DALLAS_DEGR		(0x02U)
#define EVENTS_WX_HANDLER_WARN_TEMPERATURE_DALLAS_NAV		(0x03U)
#define EVENTS_WX_HANDLER_WARN_TEMPERATURE_EXCESIVE_SLEW	(0x04U)

#define EVENTS_WX_HANDLER_WARN_PRESSURE_FAILED				(0x05U)
#define EVENTS_WX_HANDLER_WARN_HUMIDITY_FAILED				(0x06U)


#endif /* EVENTS_DEFINITIONS_EVENTS_WX_HANDLER_H_ */
