/*
 * modbus_umb.h
 *
 *  Created on: Jul 28, 2024
 *      Author: mateusz
 */

#ifndef EVENTS_DEFINITIONS_EVENTS_UMB_H_
#define EVENTS_DEFINITIONS_EVENTS_UMB_H_


#define EVENTS_UMB_WARN_CRC_FAILED_IN_RECEIVED_FRAME		(0x80U)
#define EVENTS_UMB_WARN_RECEIVED_FRAME_MALFORMED			(0x81U)
#define EVENTS_UMB_WARN_NOK_STATUS_IN_GET_STATUS_RESP		(0x82U)
#define EVENTS_UMB_WARN_NOK_STATUS_IN_OFFLINE_DATA_RESP		(0x83U)

#define EVENTS_UMB_ERROR_RECEIVING							(0xA0U)
#define EVENTS_UMB_ERROR_UNEXPECTED_ROUTINE_ID				(0xA1U)
#define EVENTS_UMB_ERROR_QF_NOT_AVAILABLE					(0xA2U)



#endif /* EVENTS_DEFINITIONS_EVENTS_UMB_H_ */
