#ifndef BUILD_DATETIME_H#define BUILD_DATETIME_H
#define BUILD_FULLYEAR 	2026
#define BUILD_YEAR 	26
#define BUILD_MONTH 	1
#define BUILD_DAY 	10
#define BUILD_HOUR 	20
#define BUILD_MINUTE 	36
#define BUILD_SECOND 	56
#define BUILD_SWVERSTR 	"10012026"

#endif
