#ifndef BUILD_DATETIME_H#define BUILD_DATETIME_H
#define BUILD_FULLYEAR 	2025
#define BUILD_YEAR 	25
#define BUILD_MONTH 	11
#define BUILD_DAY 	12
#define BUILD_HOUR 	20
#define BUILD_MINUTE 	59
#define BUILD_SECOND 	28
#define BUILD_SWVERSTR 	"12112025"

#endif
