#ifndef B203942E_D692_4A26_B619_FC9FD8E636F0
#define B203942E_D692_4A26_B619_FC9FD8E636F0

/**
 * Const definitions of string representing all events possible
 */

#include "events_definitions/events_aprs_rf.h"
#include "events_definitions/events_aprsis.h"
#include "events_definitions/events_drv_i2c.h"
#include "events_definitions/events_drv_spi.h"
#include "events_definitions/events_drv_uart.h"
#include "events_definitions/events_drv_anemometer.h"
#include "events_definitions/events_umb.h"
#include "events_definitions/events_gsm_gprs.h"
#include "events_definitions/events_http_client.h"
#include "events_definitions/events_kiss.h"
#include "events_definitions/events_main.h"
#include "events_definitions/events_modbus.h"
#include "events_definitions/events_packet_tx_handler.h"
#include "events_definitions/events_pwr_save.h"
#include "events_definitions/events_tcpip.h"
#include "events_definitions/events_wx_handler.h"

/// ==================================================================================================
///	GLOBAL VARIABLES
/// ==================================================================================================

static const char * event_log_default						= "__DEFAULT\0";

/**
 * Strings for different event sources
 */
static const char * event_log_str_src_main 				= "MAIN\0";
static const char * event_log_str_src_wx_handler 			= "WX_HANDLER\0";
static const char * event_log_str_src_pwr_save 			= "PWR_SAVE\0";
static const char * event_log_str_src_packet_tx_handler 	= "PKT_TX_HNDL\0";
static const char * event_log_str_src_aprsis 				= "APRSIS\0";
static const char * event_log_str_src_kiss 				= "KISS\0";
static const char * event_log_str_src_aprs_rf 				= "APRS_RF\0";
static const char * event_log_str_src_gsm_gprs				= "GSM_GPRS\0";
static const char * event_log_str_src_tcpip 				= "TCPIP\0";
static const char * event_log_str_src_http_client 			= "HTTP\0";
static const char * event_log_str_src_modbus 				= "RTU\0";
static const char * event_log_str_src_umb 					= "UMB\0";
static const char * event_log_str_src_drv_anemometer 		= "ANEMOMETER\0";
static const char * event_log_str_src_drv_i2c 				= "I2C\0";
static const char * event_log_str_src_drv_uart 			= "UART\0";
static const char * event_log_str_src_drv_spi 				= "SPI\0";

/**
 * Strings for different severity
 *
 */
static const char * event_log_str_severity_debug 			= "DEBUG\0";
static const char * event_log_str_severity_info 			= "INFO\0";
static const char * event_log_str_severity_info_cyclic 		= "INFO_CYCLIC\0";
static const char * event_log_str_severity_warning 			= "WARNING\0";
static const char * event_log_str_severity_error 			= "ERROR\0";
static const char * event_log_str_severity_assert 			= "ASSERT\0";
static const char * event_log_str_severity_bootup 			= "BOOTUP\0";
static const char * event_log_str_severity_timesync 		= "TIMESYNC\0";

/**
 * Strings for events generated by "main" sources
 */
static const char * event_log_str_main_bootup_complete		= "BOOTUP_COMPLETE\0";
static const char * event_log_str_main_timesync_bootup		= "TS_BOOTUP\0";
static const char * event_log_str_main_timesync_periodic	= "TS_PERIODIC\0";
static const char * event_log_str_main_timesync_ntp		= "TS_NTP\0";
static const char * event_log_str_main_info_cyclic			= "CYCLIC\0";

/**
 * Strings for events generated by "drv_anemometer" sources
 *
 */
static const char * event_log_str_drv_anemometer_no_pulses_int_fired = "NO_PULSES_INT_FIRED\0";
static const char * event_log_str_drv_anemometer_excesive_slew_rate = "EXCESIVE_SLEW\0";
static const char * event_log_str_drv_anemometer_uf_conv_not_working = "UF_CONV_NOT_WRKNG\0";
static const char * event_log_str_drv_anemometer_uf_freq_to_hi = "UF_FREQ_TOO_HI\0";
static const char * event_log_str_drv_anemometer_qf_not_full = "QF_NOT_FULL\0";

/**
 * Strings for events generated by "gsm gprs"
 */
static const char * event_log_str_tcpip_error_apn_config_missing = "NO_APN_CONFIG\0";
static const char * event_log_str_tcpip_warn_async_msg_detected = "ASYNC_MSG_DETECT\0";


/**
 * Strings for events generated by "pwr_save"
 */
static const char * event_log_str_pwr_save_going_sleep = "B+LOW_GOING_SLEEP\0";

/**
 * Strings for events generated by "tcpip"
 */
static const char * event_log_str_tcpip_error_connecting = "ERR_CONNECTING\0";
static const char * event_log_str_tcpip_error_connecting_no_modem_resp = "ERR_CONN_NO_RESP\0";


/**
 * Strings for events generated by "wx_handler" sources
 *
 * #define EVENTS_WX_HANDLER_WARN_TEMPERATURE_INT_FAILED		(0x01U)
#define EVENTS_WX_HANDLER_WARN_TEMPERATURE_DALLAS_DEGR		(0x02U)
#define EVENTS_WX_HANDLER_WARN_TEMPERATURE_DALLAS_NAV		(0x03U)
#define EVENTS_WX_HANDLER_WARN_TEMPERATURE_EXCESIVE_SLEW	(0x04U)

#define EVENTS_WX_HANDLER_WARN_PRESSURE_FAILED				(0x05U)
#define EVENTS_WX_HANDLER_WARN_HUMIDITY_FAILED				(0x06U)
 *
 *
 */
static const char * event_log_str_wx_handler_temperature_int_failed = "TEMP_INT_FAIL\0";
static const char * event_log_str_wx_handler_temperature_dallas_degraded = "DALLAS_DEGR\0";
static const char * event_log_str_wx_handler_temperature_dallas_not_avble = "DALLAS_NVBLE\0";
static const char * event_log_str_wx_handler_temperature_excesive_slew = "EXCSVE_SLEW\0";
static const char * event_log_str_wx_handler_temperature_pressure_fail = "PRESSURE_FL\0";
static const char * event_log_str_wx_handler_temperature_humidity_fail = "HUMID_FL\0";

/**
 * Strings for events generated by "aprsis" sources
 */
static const char * event_log_str_aprsis_im_not_ok_last_keepalive = "LAST_KEEPALIVE\0";
static const char * event_log_str_aprsis_im_not_ok_last_transmit = "LAST_TRANSMIT\0";
static const char * event_log_str_aprsis_warn_auth_failed = "AUTH_FAILED\0";
static const char * event_log_str_aprsis_warn_timeout_waiting_auth = "TIMEOUT_AUTH\0";
static const char * event_log_str_aprsis_warn_no_hello_message = "NO_HELLO_MSG\0";
static const char * event_log_str_aprsis_warn_timeout_waiting_hello_msg = "TIMEOUT_HELLO\0";
static const char * event_log_str_aprsis_warn_connect_failed = "CONN_FAIL\0";
static const char * event_log_str_aprsis_warn_wrong_state = "WRONG_STATE_TO_CONN\0";
static const char * event_log_str_aprsis_warn_dead_keepalive = "DEAD_KEEPALV\0";
static const char * event_log_str_aprsis_warn_dead_transmit = "DEAD_TRANSMIT\0";

#endif /* B203942E_D692_4A26_B619_FC9FD8E636F0 */
