/*
 * memory_map.h
 *
 *  Created on: May 26, 2024
 *      Author: mateusz
 */

#ifndef MEMORY_MAP_H_
#define MEMORY_MAP_H_

#define MEMORY_MAP_BOOTLOADER_START				0x08000800
#define MEMORY_MAP_BOOLOADER_END				0x0800BFFF

#define MEMORY_MAP_APPLICATION_START			0x0800C000
#define MEMORY_MAP_APPLICATION_END				0x0803C7FF

#define MEMORY_MAP_CONFIG_SECTION_FIRST_START	0x0803F000
#define MEMORY_MAP_CONFIG_SECTION_FIRST_END		0x0803F7FF

#define MEMORY_MAP_CONFIG_SECTION_SECOND_START	0x0803F800
#define MEMORY_MAP_CONFIG_SECTION_SECOND_END	0x0803FFFF

#define MEMORY_MAP_CONFIG_SECTION_DEFAULT_START 0x08040000
#define MEMORY_MAP_CONFIG_SECTION_DEFAULT_END 	0x080407FF

#define MEMORY_MAP_CONFIG_END					0x080407FF

#define MEMORY_MAP_MEASUREMENT_512K_START		0x08041000
#define MEMORY_MAP_MEASUREMENT_1M_START			0x08080000

#define MEMORY_MAP_MEASUREMENT_512K_PAGES		48
#define MEMORY_MAP_MEASUREMENT_1M_PAGES			96

#define MEMORY_MAP_EVENT_LOG_START				0x0805A800
#define MEMORY_MAP_EVENT_LOG_END				0x0807E7FF  // 0x0807CFFF

#define MEMORY_MAP_FLASH_END					FLASH_BANK1_END

#define MEMORY_MAP_SRAM1_NOINIT							0x10002000

#define MEMORY_MAP_SRAM1_LOG_AREA_START					MEMORY_MAP_SRAM1_NOINIT		        // RAM2_NOINIT (xrw)      	: ORIGIN = 0x10002000, LENGTH = 24K
#define MEMORY_MAP_SRAM1_LOG_AREA_END					(MEMORY_MAP_SRAM1_SUPERVISOR_LOG_START - sizeof(uint32_t))

#define MEMORY_MAP_SRAM1_HFAULT_LOG_32BWORDS_SIZE		13
#define MEMORY_MAP_SRAM1_HFAULT_LOG_START				(SRAM2_BASE + SRAM2_SIZE - sizeof(uint32_t) * MEMORY_MAP_SRAM1_HFAULT_LOG_32BWORDS_SIZE)
#define MEMORY_MAP_SRAM1_HFAULT_LOG_END					(SRAM2_BASE + SRAM2_SIZE - sizeof(uint32_t))       // last byte, which could be read and write

#define MEMORY_MAP_SRAM1_SUPERVISOR_LOG_32BWORDS_SIZE	30      //!< 14 entries (exec monitor and supervisor -> 28 words)  + master time at the moment of failure + crc32
#define MEMORY_MAP_SRAM1_SUPERVISOR_LOG_START           (MEMORY_MAP_SRAM1_SUPERVISOR_LOG_END - MEMORY_MAP_SRAM1_SUPERVISOR_LOG_32BWORDS_SIZE * sizeof(uint32_t))
#define MEMORY_MAP_SRAM1_SUPERVISOR_LOG_END             MEMORY_MAP_SRAM1_HFAULT_LOG_START - sizeof(uint32_t)


#endif /* MEMORY_MAP_H_ */
